### ISSUE TITLE
Nested components?

### ISSUE THREAD

**Issue by jonathanwood** [cathive/fx-guice#24]
I've been playing with fx-guice in order to reduce boilerplate fxml loading in a large Javafx application.  I have a root Pane that embeds other custom components.  I am able to annotate the root Pane with @FXMLComponent and @Inject it, using the injected object as the root of the scene.  The custom components that are embedded in the root Panes FXML are not, however, initialized.  Before I put any effort into implementing this as a PR, I wanted to see if there is already a way to do this.  Maybe I missed something?

**Comment by headcr4sh** [comment]
Hi Jonathan,

it's unforunately been quite a while since I last worked on (or with) fx-guice, so I may not know exactly what's the current status....

I am quite sure though, that embedded FXComponents used to work. The custom FXMLLoader that takes care of all the initialization routines in conjunction with the Guice-aware BuilderFactory should _actually_ do the Trick and work out-of-the-box.

I fear I won't find the time (any time soon) to further dig into your issue or provide a unit Test and/or example. PRs however will be accepted. 😉

**Comment by jonathanwood** [comment]
No problem.  I was able to solve my issue by switching to FXControllers and using fx:include in the fxml.  Thanks for the reply!
